/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DjangoApplicationCommandPanel.java
 *
 * Created on Oct 12, 2008, 10:35:36 PM
 */

package org.netbeans.modules.python.django.project.ui.customizer;


import javax.swing.JButton;
import org.openide.awt.Mnemonics;

/**
 *
 * @author Ravi Hingarajiya
 */
public class RunSqlCommandPanel extends javax.swing.JPanel {

    private JButton cancelButton = new JButton();
    private JButton okButton = new JButton();
    private String[] DjangoCommand;
    
    /** Creates new form DjangoApplicationCommandPanel */
    public RunSqlCommandPanel(String[] DjangoApplication) {

        DjangoCommand = new String[16];


        DjangoCommand[0] = "createcachetable";
        DjangoCommand[1] = "createsuperuser";
        DjangoCommand[2] = "dbshell";
        DjangoCommand[3] = "dumpdata";
        DjangoCommand[4] = "flush";
        DjangoCommand[5] = "inspectdb";
        DjangoCommand[6] = "loaddata";
        DjangoCommand[7] = "sql";
        DjangoCommand[8] = "sqlall";
        DjangoCommand[9] = "sqlclear";
        DjangoCommand[10] = "sqlcustom";
        DjangoCommand[11] = "sqlflush";
        DjangoCommand[12] = "sqlindexes";
        DjangoCommand[13] = "sqlreset";
        DjangoCommand[14] = "sqlsequencereset";
        DjangoCommand[15] = "syncdb";
        


        initComponents();
        for(String item: DjangoApplication){
            ComboBoxDjangoApplication.addItem(item);
        }
        for(String item: DjangoCommand){
            ComboBoxCommand.addItem(item);
        }

        Mnemonics.setLocalizedText(cancelButton,"cancel");//NOI18N
        Mnemonics.setLocalizedText(okButton,"OK");//NOI18N
    }
    
    public JButton getOKButton() {
        return okButton;

    }

    public JButton getCancelButton() {
        return cancelButton;
    }
    
    public String getApplicationName() {
        return String.valueOf(ComboBoxDjangoApplication.getSelectedItem()); 
    }
    
    public String getCommand() {
        return String.valueOf(ComboBoxCommand.getSelectedItem());
    }

    public String getArgs() {
        return TextFieldArgument.getText().trim();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxDjangoApplication = new javax.swing.JComboBox();
        ComboBoxCommand = new javax.swing.JComboBox();
        TextFieldArgument = new javax.swing.JTextField();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(RunSqlCommandPanel.class, "RunSqlCommandPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(RunSqlCommandPanel.class, "RunSqlCommandPanel.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(RunSqlCommandPanel.class, "RunSqlCommandPanel.jLabel3.text")); // NOI18N

        ComboBoxDjangoApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDjangoApplicationActionPerformed(evt);
            }
        });

        ComboBoxCommand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TextFieldArgument.setText(org.openide.util.NbBundle.getMessage(RunSqlCommandPanel.class, "RunSqlCommandPanel.TextFieldArgument.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(TextFieldArgument, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ComboBoxCommand, 0, 206, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ComboBoxDjangoApplication, 0, 206, Short.MAX_VALUE))
                .add(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ComboBoxCommand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(ComboBoxDjangoApplication, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(TextFieldArgument, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxDjangoApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDjangoApplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDjangoApplicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCommand;
    private javax.swing.JComboBox ComboBoxDjangoApplication;
    private javax.swing.JTextField TextFieldArgument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
