/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPropertyProjectVisual.java
 *
 * Created on Oct 1, 2008, 3:23:21 PM
 */

package org.netbeans.modules.python.django.project.template;


import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.WizardDescriptor;
import org.openide.WizardValidationException;


/**
 *
 * @author Ravi Hingarajiya
 */
public class PanelPropertyProjectVisual extends SettingsPanel implements DocumentListener {
    
    private PanelPropertyProject panel;        
    
    private NewDjangoProjectWizardIterator.WizardType type;

    /** Creates new form PanelPropertyProjectVisual */
    public PanelPropertyProjectVisual(PanelPropertyProject panel, NewDjangoProjectWizardIterator.WizardType type) {
        this.panel = panel;
        initComponents();                
        this.type = type;
        setName("Database Connection Wizard");
        
    }
    
    void validate (WizardDescriptor wizardDescriptor) throws WizardValidationException {
       // wizardDescriptor.putProperty(WizardDescriptor.PROP_ERROR_MESSAGE, "");
      //  projectLocationPanel.validate (wizardDescriptor);
    }

    boolean valid( WizardDescriptor wizardDescriptor ) {
      //  wizardDescriptor.putProperty(WizardDescriptor.PROP_ERROR_MESSAGE, ""); //NOI18N

        return true;
        
    }
    
    void read (WizardDescriptor d) {
        System.out.println("read panel");
     /*   Object lastType =  d.getProperty("wizard-type");  //NOI18N
        if (lastType == null || lastType != type) {
            //bugfix #46387 The type of project changed, reset values to defaults
            d.putProperty ("name", null);
            d.putProperty ("projdir",null);
        }
        projectLocationPanel.read (d);
        optionsPanel.read (d); */
    }
    
    void store( WizardDescriptor wizardDescriptor ) {
        
        String databaseengine = (String) DatabaseEngineField.getSelectedItem();
        String databasehost = (String) DatabaseHostField.getText().trim();
        String databasename = (String) DatabaseNameField.getText().trim();
        String username = (String) UserNameField.getText().trim();
        String password = (String) PasswordNameField.getText().trim();
        String databaseport = (String) PortField.getText().trim();


        wizardDescriptor.putProperty(NewDjangoProjectWizardIterator.DATABASE_ENGINE,databaseengine);
        wizardDescriptor.putProperty(NewDjangoProjectWizardIterator.DATABASE_HOST,databasehost);
        wizardDescriptor.putProperty(NewDjangoProjectWizardIterator.DATABASE_NAME,databasename);
        wizardDescriptor.putProperty(NewDjangoProjectWizardIterator.DATABASE_USERNAME,username);
        wizardDescriptor.putProperty(NewDjangoProjectWizardIterator.DATABASE_PASSWORD,password);
        wizardDescriptor.putProperty(NewDjangoProjectWizardIterator.DATABASE_PORT,databaseport);
    
    
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatabaseEngineLabel = new javax.swing.JLabel();
        DatabaseEngineField = new javax.swing.JComboBox();
        DatabaseNameLabel = new javax.swing.JLabel();
        DatabaseHostLabel = new javax.swing.JLabel();
        DatabaseHostField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PortField = new javax.swing.JTextField();
        DatabaseNameField = new javax.swing.JTextField();
        UserNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PasswordNameField = new javax.swing.JTextField();

        DatabaseEngineLabel.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.DatabaseEngineLabel.text")); // NOI18N

        DatabaseEngineField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "postgresql_jdbc", "mysql", "oracle", "postgresql_psycopg2", "postgresql", "sqlite3" }));
        DatabaseEngineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseEngineFieldActionPerformed(evt);
            }
        });

        DatabaseNameLabel.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.DatabaseNameLabel.text")); // NOI18N

        DatabaseHostLabel.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.DatabaseHostLabel.text")); // NOI18N

        DatabaseHostField.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.DatabaseHostField.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.jLabel2.text")); // NOI18N

        PortField.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.PortField.text")); // NOI18N
        PortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortFieldActionPerformed(evt);
            }
        });

        DatabaseNameField.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.DatabaseNameField.text")); // NOI18N

        UserNameField.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.UserNameField.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.jLabel3.text")); // NOI18N

        PasswordNameField.setText(org.openide.util.NbBundle.getMessage(PanelPropertyProjectVisual.class, "PanelPropertyProjectVisual.PasswordNameField.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, DatabaseNameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, DatabaseEngineLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, DatabaseHostLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, Short.MAX_VALUE))
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(DatabaseEngineField, 0, 300, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(PasswordNameField)
                        .add(UserNameField)
                        .add(DatabaseNameField)
                        .add(PortField)
                        .add(DatabaseHostField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DatabaseEngineLabel)
                    .add(DatabaseEngineField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(DatabaseHostLabel))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(DatabaseHostField)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(DatabaseNameLabel)
                    .add(PortField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(DatabaseNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(UserNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(PasswordNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DatabaseEngineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseEngineFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_DatabaseEngineFieldActionPerformed

    private void PortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_PortFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DatabaseEngineField;
    private javax.swing.JLabel DatabaseEngineLabel;
    private javax.swing.JTextField DatabaseHostField;
    private javax.swing.JLabel DatabaseHostLabel;
    private javax.swing.JTextField DatabaseNameField;
    private javax.swing.JLabel DatabaseNameLabel;
    private javax.swing.JTextField PasswordNameField;
    private javax.swing.JTextField PortField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void insertUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void removeUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void changedUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    
    

}
